apiVersion: v1
kind: ServiceAccount
metadata:
  name: marketplace-app-sa
  namespace: marketplace-app

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: resources-modify
  namespace: marketplace-app
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: install-ambassador
  namespace: marketplace-app
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: resources-modify
subjects:
  - kind: ServiceAccount
    name: marketplace-app-sa
    namespace: marketplace-app
roleRef:
  kind: Role
  name: resources-modify
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: install-ambassador
subjects:
- kind: ServiceAccount
  name: marketplace-app-sa
  namespace: marketplace-app
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: install-ambassador
  apiGroup: rbac.authorization.k8s.io