x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: '0.1.1'
  publishedVersionMetadata:
    releaseNote: >-
      A first initial release to test.


properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
      
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE

  images:
    dqlinstance:
      properties:
        imageDeployableVM:
          type: FULL

  STORAGE_CLASS:
    type: string
    title: StorageClass
    description: You can choose an existing StorageClass or create a new one.
    x-google-marketplace:
      type: STORAGE_CLASS
      storageClass:
        type: SSD

required:
- name
- namespace
- imageDeployableVM
- STORAGE_CLASS