x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: '1.0.0'
  publishedVersionMetadata:
    releaseNote: >-
      A first initial release to test.

  images: 
    '':
      properties:
        DEPLOYABLE_VM_IMAGE:
          type: FULL
        IMAGE_TAG:
          type: TAG

properties:
  INSTANCE_NAME:
    type: string
    x-google-marketplace:
      type: NAME

  NAMESPACE:
    type: string
    x-google-marketplace:
      type: NAMESPACE

  STORAGE_CLASS:
    type: string
    title: StorageClass
    description: You can choose an existing StorageClass or create a new one.
    x-google-marketplace:
      type: STORAGE_CLASS
      storageClass:
        type: SSD

  SERVICE_ACCOUNT:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          Name of a service account in the target namespace that
          has cluster-admin permissions. This is needed for the operator
          to manage resources.
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
            - apiGroups: ["apiextensions.k8s.io"]
              resources: ["customresourcedefinitions"]
              verbs:
                - '*'
            - apiGroups:
              - ""
              resources:
                - pods
                - services
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
                - serviceaccounts
                - namespaces
              verbs:
                - '*'
            - apiGroups:
              - apps
              resources:
              - deployments
              - daemonsets
              - replicasets
              - statefulsets
              verbs:
              - '*'
            - apiGroups:
              - extensions
              resources:
              - replicasets
              - deployments
              - daemonsets
              - statefulsets
              - ingresses
              verbs:
                - '*'
            - apiGroups:
              - batch
              resources:
              - jobs
              - cronjobs
              verbs:
              - '*'
            - apiGroups:
              - rbac.authorization.k8s.io
              resources:
              - clusterrolebindings
              verbs:
              - '*'
            - apiGroups:
              - rbac.authorization.k8s.io
              resources:
              - clusterroles
              verbs:
              - '*'
            - apiGroups:
              - rbac.authorization.k8s.io
              resources:
              - rolebindings
              verbs:
              - '*'
            - apiGroups:
              - admissionregistration.k8s.io
              resources:
              - validatingwebhookconfigurations
              verbs:
              - '*'
            - apiGroups:
              - admissionregistration.k8s.io
              resources:
              - mutatingwebhookconfigurations
              verbs:
              - '*'
            - apiGroups:
              - apiregistration.k8s.io
              resources:
              - apiservices
              verbs:
              - '*'
            - apiGroups:
              - certificates.k8s.io
              resources:
              - certificatesigningrequests
              - certificatesigningrequests/approval
              verbs:
              - create
              - delete
              - get
              - list
              - watch
              - update
            - apiGroups:
              - authentication.k8s.io
              resources:
              - tokenreviews
              - subjectaccessreviews
              verbs:
              - create

required:
- INSTANCE_NAME
- NAMESPACE
- STORAGE_CLASS
- SERVICE_ACCOUNT