x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: '0.1.1'
  publishedVersionMetadata:
    releaseNote: >-
      A first initial release to test.

  images: 
    '':
      properties:
        dqlImage:
          type: FULL

properties:
  INSTANCE_NAME:
    type: string
    x-google-marketplace:
      type: NAME

  NAMESPACE:
    type: string
    x-google-marketplace:
      type: NAMESPACE

  STORAGE_CLASS:
    type: string
    title: StorageClass
    description: You can choose an existing StorageClass or create a new one.
    x-google-marketplace:
      type: STORAGE_CLASS
      storageClass:
        type: SSD

  operatorServiceAccount:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          Monitors cluster-wide app dependencies (such as x and y),
          managing CoreOS application instances and their etcdclusters.
        roles:
        - type: ClusterRole        # This is a cluster-wide ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: view  # Use predefined role named "view"
        - type: Role               # This is a namespaced Role
          rulesType: CUSTOM        # We specify our own custom RBAC rules
          rules:
          - apiGroups: ['apps.kubernetes.io']
            resources: ['applications']
            verbs: ['*']
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
          - apiGroups: ['etcd.database.coreos.com']
            resources: ['etcdclusters']
            verbs: ['*']

required:
- INSTANCE_NAME
- NAMESPACE
- STORAGE_CLASS
- operatorServiceAccount