x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: '1.0.1-gmp1'
  publishedVersionMetadata:
    releaseNote: >-
      A first initial release to test.

  images: 
    '':
      properties:
        DEPLOYABLE_VM_IMAGE:
          type: FULL
        IMAGE_TAG:
          type: TAG
        IMAGE_REPO:
          type: REPO_WITH_REGISTRY
    ubbagent:
      properties:
        IMAGE_TAG:
          type: TAG
    nats:
      properties:
        IMAGE_TAG:
          type: TAG
    postgresql:
      properties:
        IMAGE_TAG:
          type: TAG
    caas-uniform-message:
      properties:
        IMAGE_TAG:
          type: TAG
    autoql-redisearch-service:
      properties:
        IMAGE_TAG:
          type: TAG
    autoql-integration-service:
      properties:
        IMAGE_TAG:
          type: TAG
    autoql-query-controller-service:
      properties:
        IMAGE_TAG:
          type: TAG
    autoql-user-management-service:
      properties:
        IMAGE_TAG:
          type: TAG
    autoql-notifications-service:
      properties:
        IMAGE_TAG:
          type: TAG
    autoql-credential-service:
      properties:
        IMAGE_TAG:
          type: TAG
    autoql-credential-proxy-service:
      properties:
        IMAGE_TAG:
          type: TAG
    autoql-egress-service:
      properties:
        IMAGE_TAG:
          type: TAG
    authority-service:
      properties:
        IMAGE_TAG:
          type: TAG
    autoql-excel-plugin:
      properties:
        IMAGE_TAG:
          type: TAG
    autoql-logic-engine-service:
      properties:
        IMAGE_TAG:
          type: TAG
    autoql-webapp-frontend:
      properties:
        IMAGE_TAG:
          type: TAG
    autoql-widget-support-service:
      properties:
        IMAGE_TAG:
          type: TAG
    sql-go-antlr:
      properties:
        IMAGE_TAG:
          type: TAG
    caas-integration-portal:
      properties:
        IMAGE_TAG:
          type: TAG
    autoql-redisearch-service-teams-bot:
      properties:
        IMAGE_TAG:
          type: TAG
    autoql-recommendation-service:
      properties:
        IMAGE_TAG:
          type: TAG
    sethybrid-service:
      properties:
        IMAGE_TAG:
          type: TAG
    autoql-usage-service:
      properties:
        IMAGE_TAG:
          type: TAG
    emissary-ingress:
      properties:
        IMAGE_TAG:
          type: TAG
    ambassador-agent:
      properties:
        IMAGE_TAG:
          type: TAG

properties:
  INSTANCE_NAME:
    type: string
    x-google-marketplace:
      type: NAME

  NAMESPACE:
    type: string
    x-google-marketplace:
      type: NAMESPACE

  STORAGE_CLASS:
    type: string
    description: You can choose an existing StorageClass or create a new one.
    title: Storage Class
    x-google-marketplace:
      type: STORAGE_CLASS
      storageClass:
        type: SSD

  reportingSecret:
    type: string
    title: The Secret resource name that contains the credentials for usage reports and are used by the usage-based billing agent.
    x-google-marketplace:
      type: REPORTING_SECRET

  SERVICE_ACCOUNT:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      title: Service Account
      serviceAccount:
        description: >
          Name of a service account in the target namespace that
          has cluster-admin permissions. This is needed for the operator
          to manage resources.
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
            - apiGroups: ["apiextensions.k8s.io"]
              resources: ["customresourcedefinitions"]
              verbs:
                - '*'
            - apiGroups:
              - ""
              resources:
                - pods
                - services
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
                - serviceaccounts
                - namespaces
              verbs:
                - '*'
            - apiGroups:
              - apps
              resources:
              - deployments
              - daemonsets
              - replicasets
              - statefulsets
              verbs:
              - '*'
            - apiGroups:
              - extensions
              resources:
              - replicasets
              - deployments
              - daemonsets
              - statefulsets
              - ingresses
              verbs:
                - '*'
            - apiGroups:
              - batch
              resources:
              - jobs
              - cronjobs
              verbs:
              - '*'
            - apiGroups:
              - rbac.authorization.k8s.io
              resources:
              - clusterrolebindings
              - clusterroles
              - rolebindings
              - roles
              verbs:
              - '*'
            - apiGroups:
              - admissionregistration.k8s.io
              resources:
              - validatingwebhookconfigurations
              verbs:
              - '*'
            - apiGroups:
              - admissionregistration.k8s.io
              resources:
              - mutatingwebhookconfigurations
              verbs:
              - '*'
            - apiGroups:
              - apiregistration.k8s.io
              resources:
              - apiservices
              verbs:
              - '*'
            - apiGroups:
              - certificates.k8s.io
              resources:
              - certificatesigningrequests
              - certificatesigningrequests/approval
              verbs:
              - '*'
            - apiGroups:
              - authentication.k8s.io
              resources:
              - tokenreviews
              - subjectaccessreviews
              verbs:
              - '*'
            - apiGroups:
              - policy
              resources:
              - poddisruptionbudgets
              verbs:
              - '*'
            - apiGroups:
              - getambassador.io
              resources:
              - listeners
              - mappings
              - hosts
              - modules
              verbs:
              - '*'
            - apiGroups:
              - cert-manager.io
              resources:
              - clusterissuers
              - certificates
              verbs:
              - '*'
            - apiGroups:
              - networking.k8s.io
              resources:
              - ingressclasses
              verbs:
              - '*'

  PEM_SECRET:
    type: string
    title: ENCODED PEM SECRET
    description: base64 encoded value of pem file for portal authentication. Command to encode a file:base64 -i <input_file>. Example:base64 -i deployable-integrator.pem
    x-google-marketplace:
      type: STRING

  JSON_SECRET:
    type: string
    title: ENCODED JSON SECRET
    description: base64 encoded value of service account json file for portal authentication. Command to encode a file:base64 -i <input_file>. Example:base64 -i chata-secret.json
    x-google-marketplace:
      type: STRING

  JWT_SECRET:
    type: string
    title: ENCODED JWT SECRET
    description: base64 encoded value of JWT credentials json file for portal authentication. Command to encode a file:base64 -i <input_file>. Example:base64 -i jwt-credentials-prod.json
    x-google-marketplace:
      type: STRING

  BACKEND_SUBDOMAIN:
    type: string
    title: BACKEND SUBDOMAIN
    description: Subdomain URL for the API calls
    x-google-marketplace:
      type: STRING

  PORTAL_SUBDOMAIN:
    type: string
    title: PORTAL SUBDOMAIN
    description: Subdomain URL for the portal login
    x-google-marketplace:
      type: STRING

  WEBAPP_SUBDOMAIN:
    type: string
    title: WEBAPP SUBDOMAIN
    description: Subdomain URL for the webapp login
    x-google-marketplace:
      type: STRING

  EXCEL_SUBDOMAIN:
    type: string
    title: EXCEL SUBDOMAIN
    description: Subdomain URL for the excel application login
    x-google-marketplace:
      type: STRING

  ADMIN_EMAIL:
    type: string
    title: ADMIN EMAIL
    description: Email of the Admin user to login to the portal
    x-google-marketplace:
      type: STRING

  ADMIN_FIRST_NAME:
    type: string
    title: ADMIN FIRST NAME
    description: First name of the Admin user
    x-google-marketplace:
      type: STRING  

  ADMIN_LAST_NAME:
    type: string
    title: ADMIN LAST NAME
    description: Last name of the Admin user
    x-google-marketplace:
      type: STRING    

  INTEGRATOR_BUCKET:
    type: string
    title: INTEGRATOR BUCKET
    description: Chata Google bucket where integrator model files are generated
    x-google-marketplace:
      type: STRING

  INTEGRATOR_ID:
    type: integer
    title: INTEGRATOR ID
    description: Unique ID of the Integrator. Value is an integer

  RELEASE_VERSION:
    type: string
    default: ''
    title: RELEASE VERSION
    description: Release version of the Integrator related datamodel
    x-google-marketplace:
      type: STRING

  INDEX_BUCKET:
    type: string
    title: INDEX BUCKET
    description: Chata Google bucket where integrator model buckets data is stored and used for portal installs
    x-google-marketplace:
      type: STRING

  HELM_REPO_URL:
    type: string
    title: HELM REPO URL
    description: Chata Google bucket where helm charts for the services are placed
    x-google-marketplace:
      type: STRING

  POST_DEPLOYMENTS_URL:
    type: string
    title: POST DEPLOYMENTS URL
    description: Chata Google bucket post install scripts for service configurations are placed
    x-google-marketplace:
      type: STRING

  TLS_CERTIFICATE_VALUE:
    type: string
    title: ENCODED TLS CERTIFICATE
    description: base64 encoded value of TLS certificate for emissary service https. Command to encode a file:base64 -i <input_file>. Example:base64 -i tls_certificate.json.
    x-google-marketplace:
      type: STRING

  TLS_PRIVATE_KEY_VALUE:
    type: string
    title: ENCODED TLS PRIVATE KEY
    description: base64 encoded value of TLS private key for emissary service https. Command to encode a file:base64 -i <input_file>. Example:base64 -i tls_privatekey.json.
    x-google-marketplace:
      type: STRING

  REPLICAS_OVERRIDE_VALUE:
    type: string
    default: ''
    title: REPLICAS OVERRIDE VALUE (required to override replica value in the chart file)
    description: Number of replicas of the service to override value in the chart file
    x-google-marketplace:
      type: STRING

  CPU_OVERRIDE_VALUE:
    type: string
    default: ''
    title: CPU OVERRIDE VALUE (required to override CPU value in the chart file)
    description: CPU value of the service to override value defined in the manifest
    x-google-marketplace:
      type: STRING

  SPOT_INSTANCES_ENABLED:
    type: string
    default: ''
    title: SPOT INSTANCES (required if using preemptible nodes. set to true or false)
    description: Install the deployments and statefulsets on SPOT/Preemptible nodes. Set to true or false
    x-google-marketplace:
      type: STRING

required:
- INSTANCE_NAME
- NAMESPACE
- STORAGE_CLASS
- reportingSecret
- SERVICE_ACCOUNT
- PEM_SECRET
- JSON_SECRET
- JWT_SECRET
- BACKEND_SUBDOMAIN
- PORTAL_SUBDOMAIN
- WEBAPP_SUBDOMAIN
- EXCEL_SUBDOMAIN
- INTEGRATOR_BUCKET
- INTEGRATOR_ID
- ADMIN_EMAIL
- ADMIN_FIRST_NAME
- ADMIN_LAST_NAME
- INDEX_BUCKET
- HELM_REPO_URL
- POST_DEPLOYMENTS_URL
- TLS_CERTIFICATE_VALUE
- TLS_PRIVATE_KEY_VALUE