x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: '1.0.0'
  publishedVersionMetadata:
    releaseNote: >-
      A first initial release to test.

  images: 
    '':
      properties:
        DEPLOYABLE_VM_IMAGE:
          type: FULL
        IMAGE_TAG:
          type: TAG

properties:
  INSTANCE_NAME:
    type: string
    x-google-marketplace:
      type: NAME

  NAMESPACE:
    type: string
    x-google-marketplace:
      type: NAMESPACE

  STORAGE_CLASS:
    type: string
    title: StorageClass
    description: You can choose an existing StorageClass or create a new one.
    x-google-marketplace:
      type: STORAGE_CLASS
      storageClass:
        type: SSD

  SERVICE_ACCOUNT:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          Name of a service account in the target namespace that
          has cluster-admin permissions. This is needed for the operator
          to manage resources.
        roles:
        - type: ClusterRole
          rulesType: CUSTOM
          rules:
            - apiGroups: ["apiextensions.k8s.io"]
              resources: ["customresourcedefinitions"]
              verbs:
                - '*'
            - apiGroups:
              - ""
              resources:
                - pods
                - services
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
                - serviceaccounts
                - namespaces
              verbs:
                - '*'
            - apiGroups:
              - apps
              resources:
              - deployments
              - daemonsets
              - replicasets
              - statefulsets
              verbs:
              - '*'
            - apiGroups:
              - extensions
              resources:
              - replicasets
              - deployments
              - daemonsets
              - statefulsets
              - ingresses
              verbs:
                - '*'
            - apiGroups:
              - batch
              resources:
              - jobs
              - cronjobs
              verbs:
              - '*'
            - apiGroups:
              - rbac.authorization.k8s.io
              resources:
              - clusterrolebindings
              verbs:
              - '*'
            - apiGroups:
              - rbac.authorization.k8s.io
              resources:
              - clusterroles
              verbs:
              - '*'
            - apiGroups:
              - rbac.authorization.k8s.io
              resources:
              - rolebindings
              verbs:
              - '*'
            - apiGroups:
              - admissionregistration.k8s.io
              resources:
              - validatingwebhookconfigurations
              verbs:
              - '*'
            - apiGroups:
              - admissionregistration.k8s.io
              resources:
              - mutatingwebhookconfigurations
              verbs:
              - '*'
            - apiGroups:
              - apiregistration.k8s.io
              resources:
              - apiservices
              verbs:
              - '*'
            - apiGroups:
              - certificates.k8s.io
              resources:
              - certificatesigningrequests
              - certificatesigningrequests/approval
              verbs:
              - create
              - delete
              - get
              - list
              - watch
              - update
            - apiGroups:
              - authentication.k8s.io
              resources:
              - tokenreviews
              - subjectaccessreviews
              verbs:
              - create

  PEM_SECRET:
    type: string
    default: test
    description: base64 encoded value of pem file for portal authentication
    x-google-marketplace:
      type: STRING

  # JSON_SECRET:
  #   type: string
  #   default: test
  #   description: base64 encode value of service account json file for portal authentication
  #   x-google-marketplace:
  #     type: STRING

  # JWT_SECRET:
  #   type: string
  #   default: test
  #   description: base64 encode value of JWT credentials json file for portal authentication
  #   x-google-marketplace:
  #     type: STRING

  # DOCKER_SECRET:
  #   type: string
  #   default: test
  #   description: base64 encode value of service account json file for imagepullsecret from private registry
  #   x-google-marketplace:
  #     type: STRING

  # BACKEND_SUBDOMAIN:
  #   type: string
  #   default: test
  #   description: Subdomain URL for the API calls
  #   x-google-marketplace:
  #     type: STRING

  # PORTAL_SUBDOMAIN:
  #   type: string
  #   default: test
  #   description: Subdomain URL for the portal login
  #   x-google-marketplace:
  #     type: STRING

  # WEBAPP_SUBDOMAIN:
  #   type: string
  #   default: test
  #   description: Subdomain URL for the webapp login
  #   x-google-marketplace:
  #     type: STRING

  # EXCEL_SUBDOMAIN:
  #   type: string
  #   default: test
  #   description: Subdomain URL for the excel application login
  #   x-google-marketplace:
  #     type: STRING

  # ADMIN_EMAIL:
  #   type: string
  #   default: test
  #   description: Email of the Admin user to login to the portal
  #   x-google-marketplace:
  #     type: STRING

  # ADMIN_FIRST_NAME:
  #   type: string
  #   default: test
  #   description: First name of the Admin user
  #   x-google-marketplace:
  #     type: STRING  

  # ADMIN_LAST_NAME:
  #   type: string
  #   default: test
  #   description: Last name of the Admin user
  #   x-google-marketplace:
  #     type: STRING    

  # INTEGRATOR_BUCKET:
  #   type: string
  #   default: test
  #   description: Chata Google bucket where integrator model files are generated
  #   x-google-marketplace:
  #     type: STRING

  # INTEGRATOR_ID:
  #   type: integer
  #   default: 3010
  #   description: Unique ID of the Integrator. Value is an integer
  #   x-google-marketplace:
  #     type: STRING

  # RELEASE_VERSION:
  #   type: string
  #   default: test
  #   description: Release version of the Integrator related model
  #   x-google-marketplace:
  #     type: STRING

  # INDEX_BUCKET:
  #   type: string
  #   default: test
  #   description: Chata Google bucket where integrator model buckets data is stored and used for portal installs
  #   x-google-marketplace:
  #     type: STRING

  # SPOT_INSTANCES_ENABLED:
  #   type: boolean
  #   default: false
  #   description: Install the deployments and statefulsets on SPOT/Preemptible nodes. 
  #   x-google-marketplace:
  #     type: STRING

  # DESTINATION_REGISTRY:
  #   type: string
  #   default: test
  #   description: Marketplace registry URL where services images are kept
  #   x-google-marketplace:
  #     type: STRING

  # HELM_REPO_URL:
  #   type: string
  #   default: test
  #   description: Chata Google bucket where helm charts for the services are placed
  #   x-google-marketplace:
  #     type: STRING

  # POST_DEPLOYMENTS_URL:
  #   type: string
  #   default: test
  #   description: Chata Google bucket post install scripts for service configurations are placed
  #   x-google-marketplace:
  #     type: STRING

required:
- INSTANCE_NAME
- NAMESPACE
- STORAGE_CLASS
- SERVICE_ACCOUNT
- PEM_SECRET
# - JSON_SECRET
# - JWT_SECRET
# - DOCKER_SECRET
# - BACKEND_SUBDOMAIN
# - PORTAL_SUBDOMAIN
# - WEBAPP_SUBDOMAIN
# - EXCEL_SUBDOMAIN
# - INTEGRATOR_BUCKET
# - INTEGRATOR_ID
# - ADMIN_EMAIL
# - ADMIN_FIRST_NAME
# - ADMIN_LAST_NAME
# - RELEASE_VERSION
# - INDEX_BUCKET
# - SPOT_INSTANCES_ENABLED
# - DESTINATION_REGISTRY
# - HELM_REPO_URL
# - POST_DEPLOYMENTS_URL