x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: '0.1.1'
  publishedVersionMetadata:
    releaseNote: >-
      A first initial release to test.


properties:
  INSTANCE_NAME:
    type: string
    x-google-marketplace:
      type: NAME

  NAMESPACE:
    type: string
    x-google-marketplace:
      type: NAMESPACE

  images:
    dqlinstance:
      properties:
        IMAGE_DEPLOYABLE_VM:
          type: FULL

  STORAGE_CLASS:
    type: string
    title: StorageClass
    description: You can choose an existing StorageClass or create a new one.
    x-google-marketplace:
      type: STORAGE_CLASS
      storageClass:
        type: SSD

  SERVICE_ACCOUNT:
    title: Cluster Admin Service Account
    description: >-
      Name of a service account in the target namespace that
      has cluster-admin permissions. This is needed deployable instance
      to modify other resources on the cluster.
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          # TODO(barney-s): Reduce the permission set.
          rulesFromRoleName: cluster-admin

required:
- INSTANCE_NAME
- NAMESPACE
- IMAGE_DEPLOYABLE_VM
- STORAGE_CLASS
- SERVICE_ACCOUNT