apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-tester"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
  annotations:
    marketplace.cloud.google.com/verification: test
spec:
  serviceAccountName: {{ .Values.SERVICE_ACCOUNT }}
  containers:
  - name: tester
    image: "${testerImage}"
    imagePullPolicy: Always
    env:
    - name: INSTANCE_NAME
      value: "{{ .Release.Name }}"
  restartPolicy: Never