apiVersion: v1
kind: Pod
metadata:
  name: "${INSTANCE_NAME}-tester"
  labels:
    app.kubernetes.io/name: "${INSTANCE_NAME}"
  annotations:
    marketplace.cloud.google.com/verification: test
spec:
  serviceAccountName: ${SERVICE_ACCOUNT}
  containers:
  - name: tester
    image: "${testerImage}"
    imagePullPolicy: Always
    env:
    - name: INSTANCE_NAME
      value: ${INSTANCE_NAME}
  restartPolicy: Never