apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "$INSTANCE_NAME"
  namespace: "$NAMESPACE"
  annotations:
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "dql-marketplace", "product_id": "dql", "partner_name": "dql-marketplace"}'
  labels:
    app.kubernetes.io/name: "$INSTANCE_NAME"
spec:
  descriptor:
    type: Chata DQL instance
    version: '1.0.1-gcp.alpha1'
  selector:
    matchLabels:
      app.kubernetes.io/name: "$INSTANCE_NAME"
  componentKinds:
  # The group is determined from the apiVersion: $GROUP_NAME/$VERSION
  - group: v1
    kind: PersistentVolumeClaim
  - group: v1
    kind: ServiceAccount
  - group: v1
    kind: Configmap
  - group: v1
    kind: Secret
  - group: apps/v1
    kind: Deployment
  - group: v1
    kind: Service
  - group: apps/v1
    kind: StatefulSet
  - group: batch/v1
    kind: Job
  - group: batch/v1
    kind: CronJob