kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: $INSTANCE_NAME-pvc
  labels:
    app.kubernetes.io/name: $INSTANCE_NAME-pvc
    app.kubernetes.io/component: deployable-vm-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: $STORAGE_CLASS

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: $INSTANCE_NAME
spec:
  serviceName: $INSTANCE_NAME
  replicas: 1
  selector:
    matchLabels:
      app: deployable-vm
  template:
    metadata:
      labels:
        app: deployable-vm
    spec:
      serviceAccountName: $operatorServiceAccount
      containers:
      # - image: $dqlImage
      - image: us-east1-docker.pkg.dev/dql-stag-public/dql-stag/mp-test:0.0.1
        imagePullPolicy: Always
        name: deployable-vm-image
        # lifecycle:
        #   postStart:
        #     exec:
        #       command:
        #         - sh
        #         - -c
        #         - gcloud auth activate-service-account --key-file=/var/secrets/google/chata-secret.json;
        volumeMounts:
        - name: deployable-pvc
          mountPath: "/deployable_files"
      volumes:
      - name: deployable-pvc
        persistentVolumeClaim:
          claimName: $INSTANCE_NAME-pvc        
