kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: deployable-vm-pvc
  labels:
    app.kubernetes.io/name: deployable-vm-pvc
    app.kubernetes.io/component: deployable-vm-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: $STORAGE_CLASS

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: deployable-vm
  namespace: $NAMESPACE
spec:
  serviceName: deployable-vm
  replicas: 1
  selector:
    matchLabels:
      app: deployable-vm
  template:
    metadata:
      labels:
        app: deployable-vm
    spec:
      serviceAccountName: $SERVICE_ACCOUNT
      containers:
      # - image: $DEPLOYABLE_VM_IMAGE
      - image: us-east1-docker.pkg.dev/dql-stag-public/dql-stag/dql-mp-stag:0.0.1
        imagePullPolicy: Always
        name: deployable-vm-image
        lifecycle:
          postStart:
            exec:
              command:
                - sh
                - -c
                - gcloud auth activate-service-account --key-file=/var/secrets/google/chata-secret.json;
        volumeMounts:
        - mountPath: /var/secrets/google/
          name: gcp-key
          readOnly: true
        - name: deployable-pvc
          mountPath: "/deployable_files"
      volumes:
      - name: gcp-key
        secret:
          secretName: integrator-volume-key
      - name: deployable-pvc
        persistentVolumeClaim:
          claimName: deployable-vm-pvc
      - name: deployer-configmap
        configMap:
          name: configmap-deployer             
