properties:
  testerImage:
    type: string
    default: $REGISTRY/tester:$TAG
    x-google-property:
      type: IMAGE
  PEM_SECRET:
    type: string
    default: test==
    x-google-marketplace:
      type: STRING

  JSON_SECRET:
    type: string
    default: test==
    x-google-marketplace:
      type: STRING

  JWT_SECRET:
    type: string
    default: test
    x-google-marketplace:
      type: STRING
      
  BACKEND_SUBDOMAIN:
    type: string
    default: 'api-marketplace.chata.io'
    x-google-marketplace:
      type: STRING

  PORTAL_SUBDOMAIN:
    type: string
    default: 'portal-marketplace.chata.io'
    x-google-marketplace:
      type: STRING

  WEBAPP_SUBDOMAIN:
    type: string
    default: 'webapp-marketplace.chata.io'
    x-google-marketplace:
      type: STRING

  EXCEL_SUBDOMAIN:
    type: string
    default: 'excel-marketplace.chata.io'
    x-google-marketplace:
      type: STRING

  ADMIN_EMAIL:
    type: string
    default: 'developer@chata.ai'
    x-google-marketplace:
      type: STRING

  ADMIN_FIRST_NAME:
    type: string
    default: developer
    x-google-marketplace:
      type: STRING

  ADMIN_LAST_NAME:
    type: string
    default: developer
    x-google-marketplace:
      type: STRING

  INTEGRATOR_BUCKET:
    type: string
    default: 'gs://atctest_chata-engineering_65ea66aabd53b76a6abffe06'
    x-google-marketplace:
      type: STRING

  INTEGRATOR_ID:
    type: integer
    default: 3010

  INDEX_BUCKET:
    type: string
    default: 'gs://chata-dql-index-3010-test'
    x-google-marketplace:
      type: STRING

  SPOT_INSTANCES_ENABLED:
    type: string
    default: 'true'
    x-google-marketplace:
      type: STRING

  HELM_REPO_URL:
    type: string
    default: 'gs://chata-deployable-helm-repo'
    x-google-marketplace:
      type: STRING

  POST_DEPLOYMENTS_URL:
    type: string
    default: 'gs://chata-deployable-inference'
    x-google-marketplace:
      type: STRING

  REPLICAS_OVERRIDE_VALUE:
    type: string
    default: '1'
    x-google-marketplace:
      type: STRING

  CPU_OVERRIDE_VALUE:
    type: string
    default: '0.5'
    x-google-marketplace:
      type: STRING

  TLS_CERTIFICATE_VALUE:
    type: string
    default: test
    x-google-marketplace:
      type: STRING

  TLS_PRIVATE_KEY_VALUE:
    type: string
    default: test
    x-google-marketplace:
      type: STRING
