properties:
  testerImage:
    type: string
    default: $REGISTRY/tester:$TAG
    x-google-property:
      type: IMAGE
  PEM_SECRET:
    type: string
    default: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF5WGpRWms5cEl6VTdma1NFeGdDegpOSklaOXNyYWlTRFhoSE9UUlpLUi9QSjMxdGV4TnJLL0pCM2FCam56V28wK0tNc1NSWkoxM0NaQzlQYjhLRkFMCk5QMVFjb3czcW9UM3lvZzA3c3lUUm1VOHJTemh4cUJua01EMmI0amhEdU5YM3ozSUVobEVVS09ZdEpGdktiRC8KdGFsL001U3g4cGNqalNSVVIybTUwYS9LY0Y0SnVvY1p2a0NMYldob01RV09TdEpPWkdyKzBlR05JNktvWnJOTwpIVmlnOWpMOU1vRmg2L1pRc3YxREpSKzNNY3REUHZFNENJdVBFeDU3ZWl0QnBHZ1ZiNUl3L0Q2M2paR093eHBaClNhOFRRVzVGeXZkTnRhWXRuZ3ErNkUzQjd2b1FhMHVONlROcTk4K2N4Q1pMNjNqT052YnFoMjg0dVlnVFFEdVEKV1FJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
    x-google-marketplace:
      type: STRING

  JSON_SECRET:
    type: string
    default: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAicG9ydGFibGUtZGVwbG95IiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiZTcyNDMzZmRiYzE1ZjBlMTllNTM2NTRjZWQzMzY5MDg5NGVlMDQwZSIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZRSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2N3Z2dTakFnRUFBb0lCQVFESmVOQm1UMmtqTlR0K1xuUklUR0FMTTBraG4yeXRxSklOZUVjNU5Ga3BIODhuZlcxN0Uyc3I4a0hkb0dPZk5halQ0b3l4SkZrblhjSmtMMFxuOXZ3b1VBczAvVkJ5akRlcWhQZktpRFR1ekpOR1pUeXRMT0hHb0dlUXdQWnZpT0VPNDFmZlBjZ1NHVVJRbzVpMFxua1c4cHNQKzFxWDh6bExIeWx5T05KRlJIYWJuUnI4cHdYZ202aHhtK1FJdHRhR2d4Qlk1SzBrNWthdjdSNFkwalxub3FobXMwNGRXS0QyTXYweWdXSHI5bEN5L1VNbEg3Y3h5ME0rOFRnSWk0OFRIbnQ2SzBHa2FCVnZrakQ4UHJlTlxua1k3REdsbEpyeE5CYmtYSzkwMjFwaTJlQ3I3b1RjSHUraEJyUzQzcE0ycjN6NXpFSmt2cmVNNDI5dXFIYnppNVxuaUJOQU81QlpBZ01CQUFFQ2dnRUFUS0FQOXRGK0JiK0J2SkRYeEt6UWU0NlRwR3JiZWVzTlBObHVLamhJSU9HaFxuRll1Y1lWYlRYcXVoMTl0amhFMlMxaFlDQVlibUg1Qkh4LzVGd2hsTFllQjBIOVRYZVJtd1dvMjZRQlo3YnZzaVxuL0NSRlRIT0dZQ1lidENqbG0vRjRZcllQS1Y4RnZmdXlvUDV0UG5pTWtLMkI3UDdCUFNnaGc5Vk0zb3BGKzRzSVxuakZlb2dvc3g3S1hKOU9CMXNnNjR6ZUllQlNDenNIeUg1RVFIR1NnVWQvWGx4Y2J6cGVQNzBVaWd4dmtXaXR0NVxuZ3NrMUxsM3VqUjVSQy95YTRFTEFLZVJSTUpJK3JuVmxYaE1mdWxmMFJsV0JOQmRRS2JNS2RHYVJCcEV0KzJiZFxuTzBnWEw1UUI1dC9CcklDY09Oc0xoRXhSdHh3d1U5SUhudlorQjdFZHZ3S0JnUUQyUndZRXVldXJxS1poQkNLbFxuZkJqRW81SW9CRlpiT0plOStkNStxMUplSGdVRkQxTGhhbHQrK0d3dGpxeTd3VFErQlhTNTRGOGhpVWpydHVodFxuTGVWejZPU1p1MDU5d0k5aXRGMXRYZDFpLzJJKzJmMjVYTFlWVXcydWZiSjJyWkZjczR1ZW9VcTdtR2M0SVhpdFxuT3phUzFJcFkyd3RpbWtkclNaRUErUjB4cHdLQmdRRFJiUGZ3aFUwZ2t1QXdpVE1WTGZXeTZjSTZab1hzL0VkL1xuNVk0TEg2ZGx6NkxyM2ZQK1FXVnkvUnR6U0VpYTNTdFdXbWpqK0lhZ2NPeUVjK3luT29pMldFZDU4dk9uVCtCSVxuYm55cks3eDhZQXVWMWFTZzBWVk5oeHpVTjRuMTU1RHR5ZVJHUEI0d3g5NUkzWFJHeUxnaWVRWElhR3p0QThYWFxua0hNcjFFVnQvd0tCZ1FEREhrUXJiRzNHUThrRjVqUFk3bmZsR3o4SnkxM3J5ZXVYRFNkMUxpRUZCajJ0NDVValxubUpOREJta1dzd294ZXdINy9YQ2NiNktQUEdoMHNDWjNrYnhQMS8xOXV3T1Y2QUR5RDdwUmt1TjZzcUZROEg3dlxuNC84eTUrbFlES2hmRkdhdGptYVkyR3NRTTgvYmpkRkJWaitIbHpMQThWS1UzV3ltR05QMGRHbm4wd0tCZ0FiUVxuR0xER1pWL3Q1MFVzOFhCNjhrZER1NEhTM0FCOXBJWFFuZkpXc1VkcW5jNDJoajE3T3lXbWZrSWQwOTdWMnhjUVxuRWVGNHNFaC80L0hiSTVPOUg3MXUyY1JwMXV0V2VlRmhWc1RxdzFMNGZPZis3MEFjRHo1YWF1R3NmTngzRUF2c1xuU1hUUGQ5djJaSkRTUTNvYUJZTjVsR3FVbXhhS3pPRGFYaVRLM3dkWkFvR0FDNmFybE9ya1g0bkFnNUJQeHZtalxuaFY1a0JzTEJIWkdCRHBlSitCaDBDaW0wRmNSR2V6U0NSd3JNMEZiUTh3KzZBV0hPUVlneVl4Y0dvdVRLeElpaVxuQkYyd2tMeWhzQmZrQklPaFdZOFppb0VSS1RuSlRvajZlQ1VORHF6SkFSbmJQMEhsbi9GYVlTWktvMG02NlViR1xuMEFVL1ZqRDJBd3V4TlhNNktjMkJEbms9XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAiZHFsLTMwMTAtdGVzdEBwb3J0YWJsZS1kZXBsb3kuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTEwMzc5NjY0NTIxODExMzA1NzI4IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9kcWwtMzAxMC10ZXN0JTQwcG9ydGFibGUtZGVwbG95LmlhbS5nc2VydmljZWFjY291bnQuY29tIgp9Cg==
    x-google-marketplace:
      type: STRING

  JWT_SECRET:
    type: string
    default: eyJzZWNyZXRfa2V5IjogInhwU2djbUd6dGUyNkN4b3RUMUllVkcyTTdVRWg2MDkwZEFIRHRUQ1lHR3gtN29PUndlVm16dkxIMHljeUxTQnFYaHBqZHFLVW9KUEF5ZUpqMlpLYUQ0SXVNMGZfMW1XbUVCSF9ONFliSUpEMTUtSUhhNHpvNGhaa1dKaTJtYnBPTjY2emtFNUw4Nk5LR2hRcmUzZDF2NnYzSHJEWEJEb3BVcWhDZ0ZQdk91ZFhORWw0VGlSUmk3ZTlUZnRoTVh0TTJ5OFpFd2M5cUV3RzhORnNzT0ktbHBVTzRJNVZZVm9iTVREMUU2c3dtMjdfS2xZeDEwa1Z2bzFuemhOam1PMlVHN1pxZXVPc2I1WFZGMDF4Z3Y2N0EtTTJPcU9MalFQcDV4OXJiMUVWSno5d1MyN0QtTk1PZklkYV8tVWdHbTBsUVIxR3dIU2YwV2doX0M4WXNaX0xidkNKeXlsRGRqMUxwVGJyYmt5WVItM25pZXh6OHFVT1RsWWVKN1pZV0NHMHFUOHlIRUpYbWVGdWltOFlsbHNxOFZhRm1wOEpwa3dkT0dRMXJVVm9iYXZhb1k1YWNYTDF5b2xHOWx1YUx0RG53Sks2WjZ2MDl6OExVS3VTSm1xd3NvOHBSY0YzbDcwMlNhNXhZR1E2S2pRLTU3V0pYNENZMGlPazJZNHd1dTFFVUVIakxuU1pFRUozVHU1NUlwalRXMERvWGlpRDJqWlR5Zm8xd3pfUE1hdURKSUJLaEtVWXhucjFvVkQxUzFIbHl4NnNWVUNtcUUzbTdFQ2tIdVllWC12aTJtNGs1UXk2am8wUm9PTkpWRi1CbEQyMmJkNGFRZmRubFRKd2xLNHlzUFBVR3QxVzN3S3ZTVVFvV0lnZFRGeTdtYnlXX1ljRzBnelZjaV9zdGZVIiwgImF1ZGllbmNlIjogImI3ZmY1NTQwLTI2MmMtNDA0ZS05ZWRkLWRiYTE0MWE5MWZjMyJ9
    x-google-marketplace:
      type: STRING
      
  BACKEND_SUBDOMAIN:
    type: string
    default: 'api-marketplace.chata.io'
    x-google-marketplace:
      type: STRING

  PORTAL_SUBDOMAIN:
    type: string
    default: 'portal-marketplace.chata.io'
    x-google-marketplace:
      type: STRING

  WEBAPP_SUBDOMAIN:
    type: string
    default: 'webapp-marketplace.chata.io'
    x-google-marketplace:
      type: STRING

  EXCEL_SUBDOMAIN:
    type: string
    default: 'excel-marketplace.chata.io'
    x-google-marketplace:
      type: STRING

  ADMIN_EMAIL:
    type: string
    default: 'developer@chata.ai'
    x-google-marketplace:
      type: STRING

  ADMIN_FIRST_NAME:
    type: string
    default: developer
    x-google-marketplace:
      type: STRING

  ADMIN_LAST_NAME:
    type: string
    default: developer
    x-google-marketplace:
      type: STRING

  INTEGRATOR_BUCKET:
    type: string
    default: 'gs://atctest_chata-engineering_65ea66aabd53b76a6abffe06'
    x-google-marketplace:
      type: STRING

  INTEGRATOR_ID:
    type: integer
    default: 3010

  INDEX_BUCKET:
    type: string
    default: 'gs://chata-dql-index-3010-test'
    x-google-marketplace:
      type: STRING

  SPOT_INSTANCES_ENABLED:
    type: string
    default: 'true'
    x-google-marketplace:
      type: STRING

  HELM_REPO_URL:
    type: string
    default: 'gs://chata-deployable-helm-repo'
    x-google-marketplace:
      type: STRING

  POST_DEPLOYMENTS_URL:
    type: string
    default: 'gs://chata-deployable-inference'
    x-google-marketplace:
      type: STRING

  REPLICAS_OVERRIDE_VALUE:
    type: string
    default: '1'
    x-google-marketplace:
      type: STRING

  CPU_OVERRIDE_VALUE:
    type: string
    default: '0.5'
    x-google-marketplace:
      type: STRING

  TLS_CERTIFICATE_VALUE:
    type: string
    default: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU1RENDQTh5Z0F3SUJBZ0lTQk92TkI5OUVlOGFoREhsWERyaWV4QkM3TUEwR0NTcUdTSWIzRFFFQkN3VUEKTURNeEN6QUpCZ05WQkFZVEFsVlRNUll3RkFZRFZRUUtFdzFNWlhRbmN5QkZibU55ZVhCME1Rd3dDZ1lEVlFRRApFd05TTVRBd0hoY05NalF3T1RJd01qRXpPVEF5V2hjTk1qUXhNakU1TWpFek9UQXhXakFWTVJNd0VRWURWUVFECkRBb3FMbU5vWVhSaExtbHZNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQW5ObTkKVDF1SHdTWGlFc3NvNWEwMnE0aktpNFREUXltS2JGVkU5ZEpZWHYrd20vR3JxSHRVMUE4Q3FieXQwL2syd09ndQp5bUZYY2ZzUno1MzVzeXl4UFRhVjJKc0NRdVpJWGh1NmFmSW4yZTRlT2d4YThRb2lQb1dBK09MV3g5YXRGQWpQCjZSS3E4THNCNVVsbEFwRnVLY2tWWTZyR0k3QmMzend3RlVRQkJHR3NaZVBpdHhBZ25EREN2cnFYelNIa0h6SkIKYXdNYnY1RzdsT2x6WXZuTlRhUHNQUzNWZ09IRi9FeVJYWWhoZUtUVWFCVjhabFVFeGExVFgxM29LNG5pdGZmQwo5cFcxVkJ1TDBtMXBkOC80UmhEYUlvVXptRitFbE1JM2RWN2kwczNYQlhSdmEyMmx2WkdtTUFtWVNXbkY2QWN0Cm9OUmRQTTcwNzdFdGw4dWQ0d0lEQVFBQm80SUNEakNDQWdvd0RnWURWUjBQQVFIL0JBUURBZ1dnTUIwR0ExVWQKSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CMEdBMVVkRGdRVwpCQlJpRHF6SzA5Y05HczU2L2RKdy9nSmZ1dWFqbGpBZkJnTlZIU01FR0RBV2dCUzd2TU5IcGVTOHFjYkRwSElNCkVJMmlOZUhJNkRCWEJnZ3JCZ0VGQlFjQkFRUkxNRWt3SWdZSUt3WUJCUVVITUFHR0ZtaDBkSEE2THk5eU1UQXUKYnk1c1pXNWpjaTV2Y21jd0l3WUlLd1lCQlFVSE1BS0dGMmgwZEhBNkx5OXlNVEF1YVM1c1pXNWpjaTV2Y21jdgpNQlVHQTFVZEVRUU9NQXlDQ2lvdVkyaGhkR0V1YVc4d0V3WURWUjBnQkF3d0NqQUlCZ1puZ1F3QkFnRXdnZ0VFCkJnb3JCZ0VFQWRaNUFnUUNCSUgxQklIeUFQQUFkUUJJc09OcjJxWkhOQS9sYWdMNm5URHJIRklCeTFiZExJSFoKdTcrck9kaUVjd0FBQVpJUmxWaDNBQUFFQXdCR01FUUNJRmhVUEJWeEpHNVRRYWN6OUg0cld0S1JQM3ZyLzRCaApJU04xcnZIK1dramxBaUFDcnRtOVNHcEFITjdWNGF3Wkd2aXNhYkIyeTBIUFZEd25JTG5pYnVqcmpnQjNBTi9oClZ1dXFCYSsxbkErR2NZMm93REpPcmxiWmJxZjFwV29CMGNFN3ZsSmNBQUFCa2hHVldUUUFBQVFEQUVnd1JnSWgKQU9vbzBIOVlYNkNlRmRTYysxSTg2RlZvVTE2bGsybU0zNnR2TGNUL3IzeG9BaUVBcTVldC9reXRjdTZ5ajJDeQpBdDNNUnRML0dpeVBHUVpMTVRsLzF0ZTF2OU13RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUFJR1hHNDBNclFqCkZTZTBHR2NZTmV5V0xFNHQ0L2hBMFdmeFBaL1o2YjdXM3p0ajdxSzR2V0Q3QjZhcFh4cWY2RmF4MDVOT3lBZTUKTSt4Mmc0d2NRc2RuUWtGazIvQ092YVV0UEF1d04rSlhZcnJpWC9zTGtCYkF1bnB6S21Iak9oUXVhSzUzeENaWgpOWm5mdzB6bjk4RHJYdHY1bDFpbGsxOTJsOFo0bUcyYkdNL2xsUjhjU1VIREN1NjlaM2szK3JUZldzOEhxMU1uCjhDNUE1V01rUHNDNjNuS3ZQQ1N3eDRIKzYyTHFTYzkxWGltVlJ0S1kxV3orTW1SVmFKTEUxaUNOQWxIMFgyR1oKa2ttSFpwU2I2eFNHQSsrVkd5dDBVM3VrV2tuakZoL2J2MGFNYkFPanZYTksxZUFwZEtaVDV2WHFqL3UxRHNSZQpZV3pKZm9aVGxZZz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRkJUQ0NBdTJnQXdJQkFnSVFTNmhTay9lYUw2SnpCa3VvQkkxMTBEQU5CZ2txaGtpRzl3MEJBUXNGQURCUApNUXN3Q1FZRFZRUUdFd0pWVXpFcE1DY0dBMVVFQ2hNZ1NXNTBaWEp1WlhRZ1UyVmpkWEpwZEhrZ1VtVnpaV0Z5ClkyZ2dSM0p2ZFhBeEZUQVRCZ05WQkFNVERFbFRVa2NnVW05dmRDQllNVEFlRncweU5EQXpNVE13TURBd01EQmEKRncweU56QXpNVEl5TXpVNU5UbGFNRE14Q3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEVlFRS0V3MU1aWFFuY3lCRgpibU55ZVhCME1Rd3dDZ1lEVlFRREV3TlNNVEF3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURQVitYbXhGUVM3YlJIL3NrbldIWkdVQ2lNSFQ2STN3V2QxYlVZS2IzZHRWcS8rdmJPbzc2dkFDRkwKWWxwYVBBRXZ4VmdEOW9uL2poRkQ2OEcxNEJRSGxvOXZIOWZudW9FNUNYVmx0OEt2R0ZzM0ppam5vL1FISzIwYQovNnRZdkpXdVFQL3B5MWZFdFZ0L2VBMFlZYndYNTFUR3UwbVJ6VzRZMFlDRjdxWmxOcngwNnJ4UVRPcjhJZk00CkZwT1V1ckRUYXpnR3pSWVNlc3BTZGNpdGRyTENuRjJZUlZ4dllYdkdMZTQ4RTFLR0FkbFg1amdjMzQyMUg1S1IKbXVkS0hNeEZxSEpWOExEbW93ZnMvYWNiWnA0L1NJdHhoSEZZeVRyNjcxN3lXMFFyUEhUbmo3Skh3UWRxelpxMwpEWmIzRW9FbVVWUUs3R0gyOS9YaThvcklsUTJOQWdNQkFBR2pnZmd3Z2ZVd0RnWURWUjBQQVFIL0JBUURBZ0dHCk1CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFTQmdOVkhSTUJBZjhFQ0RBR0FRSC8KQWdFQU1CMEdBMVVkRGdRV0JCUzd2TU5IcGVTOHFjYkRwSElNRUkyaU5lSEk2REFmQmdOVkhTTUVHREFXZ0JSNQp0Rm5tZTdibDVBRnpnQWlJeUJwWTl1bWJiakF5QmdnckJnRUZCUWNCQVFRbU1DUXdJZ1lJS3dZQkJRVUhNQUtHCkZtaDBkSEE2THk5NE1TNXBMbXhsYm1OeUxtOXlaeTh3RXdZRFZSMGdCQXd3Q2pBSUJnWm5nUXdCQWdFd0p3WUQKVlIwZkJDQXdIakFjb0JxZ0dJWVdhSFIwY0RvdkwzZ3hMbU11YkdWdVkzSXViM0puTHpBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FnRUFrckhuUVRmcmVaMkI1czNpSmVFNklPbVFSSldqZ1Z6UHcxMzl2YUJ3MWJHV0tDSUwwdklvCnp3em4xT1pEakNRaUhjRkNrdEVKcjU5TDlNaHdUeUFXc1ZyZEFmWWYrQjloYXhRbnNIS05ZNjd1NHM1THp6ZmQKdTZQVXplZXRVSzI5ditQc1BtSTJjSmt4cCtpTjNlcGk0aEt1OVp6VVBTd01xdENjZWI3cVBWeEVicFl4WTFwOQoxbjVQSktCTEJYOWViOUxVNmw4elN4UFdWN2JLM2xHNFhhTUpnblQ5eDNpZXM3bXNGdHBLSzViRHRvdGlqL2wwCkdhS2VBOTdwYjV1d0Q5S2dXdmFGWE1JRXQ4alZUakxFdndSZHZDbjI5NEdQREYwOFU4bEFrSXY3dGdobHVhUWgKMVFubEU0U0VONExPRUNqOGRzSUdKWHBHVWszYVUzS2tKejlpY0t5K2FVZ0ErMmNQMjF1aDZOY0RJUzNYeWZhWgpRam1EUTk5M0NoSUk4U1hXdXBRWlZCaUlwY1dPNFJxWmszbHI3Qno1TVVDd3pESUEzNTllNTdTU3E1Q0NrWTBOCjRCNlZ1bGs3TGt0ZndyZEdOVkk1QnNDOXFxeFN3U0tnUkplWjl3eWdJYWVoYkhGSEZoY0JhTURLcGlabEJIeXoKcnNubmxGWENiNXM4SEtuNUxzVWdHdkIyNEw3c0dOWlAyQ1g3ZGhIb3YrWWhEK2pvekxXMnA5VzQ5NTlCejJFaQpSbXFEdG1pWExuenFUcFhiSStzdXlDc29oS1JnNlVuMFJDNDcrY3BpVndIaVhaQVcrY244ZWlOSWpxYlZnWEx4CktQcGR6dnZ0VG5PUGxDN1NRWlNZbWR1bnIzQmY5Yjc3QWlDL1ppZHN0SzM2ZFJJTEt6N09BNTQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0=
    x-google-marketplace:
      type: STRING

  TLS_PRIVATE_KEY_VALUE:
    type: string
    default: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRQ2MyYjFQVzRmQkplSVMKeXlqbHJUYXJpTXFMaE1OREtZcHNWVVQxMGxoZS83Q2I4YXVvZTFUVUR3S3B2SzNUK1RiQTZDN0tZVmR4K3hIUApuZm16TExFOU5wWFltd0pDNWtoZUc3cHA4aWZaN2g0NkRGcnhDaUkraFlENDR0YkgxcTBVQ00vcEVxcnd1d0hsClNXVUNrVzRweVJWanFzWWpzRnpmUERBVlJBRUVZYXhsNCtLM0VDQ2NNTUsrdXBmTkllUWZNa0ZyQXh1L2tidVUKNlhOaStjMU5vK3c5TGRXQTRjWDhUSkZkaUdGNHBOUm9GWHhtVlFURnJWTmZYZWdyaWVLMTk4TDJsYlZVRzR2UwpiV2wzei9oR0VOb2loVE9ZWDRTVXdqZDFYdUxTemRjRmRHOXJiYVc5a2FZd0NaaEphY1hvQnkyZzFGMDh6dlR2CnNTMlh5NTNqQWdNQkFBRUNnZ0VBQnR0WjlFc3JEeDJKMllwNkdqaE5TSWh0V2xZT2R6UXNzZm0wVHc3SUFEY3IKVUZYclRDMUFFeGtvNDZTMDhLeFhZVzJGQmlIbFFiMVpGUHR4L0F3N0gxTHdrQXlPdDcvN2IrbkVaM2RIbUxaWgpLZTU2VjBrN0lBS1VGYzFNMkdXaElWd1ZRcm9uTU9qcjkwc1RHRjZsTXp4d0svQStRemNsaURqSVhWV2d1Y0U5CjBTbG1hSDYvNkJLZHpwUE55eHNuQ05JRTBwMEhrVU9PM0lnbWxTUE5oN3YrU09jZDZrNjZGTGViL1IwVkpET3AKZGlRQ3hEVVVrRStmUjNBcXNWbko3WWlmZGJSemFrNVp4eUNCTlRVUGtJYnhZZ0hBR2lRdUd3eG1LSzJYb2trQwptME5uYjJmWHNvMG1wQkxnYzU0T0I5NXhlRFpMbGJZSFZEeE1tbThqVVFLQmdRREJhSFE5MTFzVTljTmt3LzVRCmJ6NUM0dDBBRUFWVlZncVFacXpKU0htaU1jdm5JTytyV1J6djBnM0crLyt3ZEN1MlMyUXRmb2c0eGpzR1JhbXkKM1h2NEo5bzJjbjNTcnlFQk9UL1dSMkY4amNJaW1OVDg1NzRiTzZhTUhOQ05nNTlFVVRta1o1UHJlekNERU9yZwoza3FjSjdSUnBYcFBKMjA1R2VZWW9rTU1DUUtCZ1FEUG5JNkNlMWtuUnNWN0xsUGhQaXhhQmRKNDkzYStuTGQvCmhlUjJLYWdNeFFpM1lhS2RlVXErY2tyaE1PczUrTi9udG9TNmp0RWJPRms2c0NMKzdtYjZRSzkzQ3FzNFJIODUKbWNjOEFWRmZ5ZlJNYUJSSDJ3eHZsUnZyT2pLZ3ZEblhaSjB5ODNsT0d2emRVTmdVWkYvNTlCdFhEYkMvTHVIZApPdUxkVUxLdGl3S0JnR1FnK0xVZmJoY2UyU2FzMVZlOUQrVyszNTF0cmVVdEkxRDQ1eEZhQlNhMFV4VDRsendGCmFaYTdEOGpwbzhrdGk0Zlg1aWdyYnNpOXo4Y0NmOFdMSnVnbGNiSm9lYjErVHo3NzdaRzQ2TDU4QVhxNTF1S0wKODM3VDFmaUozbXExTHRwR2x1b0hlYXdhM2RXdEIzeWRlTkQ1T1VCZnhEK0FjT3B6L3d6WHpKQkpBb0dBRU04QwpFcnBkMjNvMVh1Vy9VTXN4MkJBRW5GcWN1STREcFVWMzI4RS9vOWtIL2FEZ0E1UGdZMDdwbFJYYTFaUzZ2QTNnCjdTSEcrRWMxb2pURWdKTllyd1l4cnBla2lTZXlqVDFRRGlHbEx2WXcyMGJKN1k5a2tGd29LSUZMdkF2Qk94a2cKU1JIQlRudU00WFk4S0ZxQUVzS2F2QStWc2NUZjhJTmwvcmtiM2tVQ2dZQkM5aDJOVE16ZTN6MTBKblZUbWNBdgpJMmJqTXZyeldTaElVSCtwOFk2S2R2TkZJMlpncVJ5ZEtFZ094QW04SEcwMmtXWFZyMGhzUHNFOFA1RS9oRUFWCmJ2ZkROVllKTW1haWZrWHA5S2VPbHFMMVl5SGF5bDMzTnpXVzVYZnNOd0xqb25mMVdVbi8remZBRW1Qb3pwcHMKZXpTclJBejVUYk1iL2Vvc3Nzb2ViZz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
    x-google-marketplace:
      type: STRING
