apiVersion: v2
name: dql-marketplace
description: A Helm chart to deploy DQL application from Azure Marketplace Kubernetes
home: https://github.com/chatatechnologies/chart-dql-marketplace
version: 1.0.0
appVersion: "1.0.0"