apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deployable-vm-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Release.Name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  STORAGE_CLASS: {{ .Values.statefulset.persistence.storageClass }}