---
apiVersion: v1
kind: Secret
metadata:
  name: deployable-integrator-pem
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: "{{ .Release.Name }}-pem"
type: Opaque
data:
  deployable-integrator.pem: "{{ .Values.secrets.PEM_SECRET }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: integrator-volume-key
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: "{{ .Release.Name }}-volume"
type: Opaque
data:
  chata-secret.json: "{{ .Values.secrets.JSON_SECRET }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: user-auth-volume
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: "{{ .Release.Name }}-auth"
type: Opaque
data:
  jwt-credentials-prod.json: "{{ .Values.secrets.JWT_SECRET }}"

---

apiVersion: v1
kind: Secret
metadata:
  name: autoql-tls-cert
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: "{{ .Release.Name }}-tls"
type: kubernetes.io/tls
data:
  tls.crt: "{{ .Values.secrets.TLS_CERTIFICATE_VALUE }}"
  tls.key: "{{ .Values.secrets.TLS_PRIVATE_KEY_VALUE }}"
